version: "3.8"

services:
  lychee:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/lychee
    ports:
      - "90:9000"
    environment:
      - APP_ENV=production
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www/lychee
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - lychee
